import * as assert from 'assert';
import { generateFlagTypes } from '../services/codegenService';
import { FeatureFlag } from '../models/types';

function makeFlag(overrides: Partial<FeatureFlag> & { key: string }): FeatureFlag {
    return {
        id: overrides.id ?? 1,
        key: overrides.key,
        name: overrides.name ?? overrides.key,
        active: overrides.active ?? true,
        filters: overrides.filters ?? {},
        rollout_percentage: overrides.rollout_percentage ?? null,
        created_at: overrides.created_at ?? '2024-01-01T00:00:00Z',
        created_by: overrides.created_by ?? null,
        deleted: overrides.deleted ?? false,
    };
}

suite('codegenService — generateFlagTypes', () => {

    test('empty flags array returns valid header-only .d.ts string', () => {
        const result = generateFlagTypes([]);
        assert.ok(result.includes('declare namespace PostHogFlags'), 'should contain namespace declaration');
        assert.ok(result.includes('// .posthog.d.ts - generated by PostHog for VSCode'), 'should contain header comment');
        assert.ok(result.includes('// Generated:'), 'should contain generated timestamp');
        assert.ok(result.includes('// Flags: 0'), 'should show 0 flags');
        assert.ok(result.includes('// Do not edit manually'), 'should contain do not edit comment');
    });

    test('deleted flags are excluded from output', () => {
        const flags = [
            makeFlag({ key: 'active-flag', deleted: false }),
            makeFlag({ key: 'deleted-flag', deleted: true }),
        ];
        const result = generateFlagTypes(flags);
        assert.ok(result.includes('active-flag') || result.includes('"active-flag"'), 'should contain active flag');
        assert.ok(!result.includes('deleted-flag'), 'should NOT contain deleted flag');
        assert.ok(result.includes('// Flags: 1'), 'should count only non-deleted flags');
    });

    test('boolean flag without payload produces type boolean', () => {
        const flags = [makeFlag({ key: 'my_bool_flag', filters: {} })];
        const result = generateFlagTypes(flags);
        assert.ok(result.includes('boolean'), 'type should be boolean');
    });

    test('boolean flag with empty payloads object produces type boolean', () => {
        const flags = [makeFlag({ key: 'my_bool_flag', filters: { payloads: {} } })];
        const result = generateFlagTypes(flags);
        assert.ok(result.includes('boolean'), 'type should be boolean');
    });

    test('boolean flag with null payload value produces type boolean', () => {
        const flags = [makeFlag({ key: 'bool_null', filters: { payloads: { true: null } } })];
        const result = generateFlagTypes(flags);
        assert.ok(result.includes('boolean'), 'type should be boolean');
    });

    test('string payload produces type string', () => {
        const flags = [makeFlag({ key: 'str_flag', filters: { payloads: { true: '"hello"' } } })];
        const result = generateFlagTypes(flags);
        assert.ok(result.includes('string'), 'type should be string');
    });

    test('number payload produces type number', () => {
        const flags = [makeFlag({ key: 'num_flag', filters: { payloads: { true: '42' } } })];
        const result = generateFlagTypes(flags);
        assert.ok(result.includes('number'), 'type should be number');
    });

    test('boolean payload value produces type boolean', () => {
        const flags = [makeFlag({ key: 'bool_payload_flag', filters: { payloads: { true: 'true' } } })];
        const result = generateFlagTypes(flags);
        assert.ok(result.includes('boolean'), 'type should be boolean');
    });

    test('null JSON payload produces type null', () => {
        const flags = [makeFlag({ key: 'null_flag', filters: { payloads: { true: 'null' } } })];
        const result = generateFlagTypes(flags);
        assert.ok(result.includes('null'), 'type should contain null');
    });

    test('object payload produces inline interface type', () => {
        const flags = [makeFlag({ key: 'obj_flag', filters: { payloads: { true: '{"theme":"dark","version":2}' } } })];
        const result = generateFlagTypes(flags);
        assert.ok(result.includes('theme'), 'type should contain theme property');
        assert.ok(result.includes('version'), 'type should contain version property');
        assert.ok(result.includes('string'), 'theme should be string type');
        assert.ok(result.includes('number'), 'version should be number type');
    });

    test('nested object within 3 levels produces inline type', () => {
        const flags = [makeFlag({
            key: 'nested_flag',
            filters: { payloads: { true: '{"outer":{"inner":"value"}}' } }
        })];
        const result = generateFlagTypes(flags);
        assert.ok(result.includes('outer'), 'should contain outer property');
        assert.ok(result.includes('inner'), 'should contain inner property');
    });

    test('nested object deeper than 3 levels produces Record<string, unknown>', () => {
        const payload = JSON.stringify({
            l1: { l2: { l3: { l4: 'deep' } } }
        });
        const flags = [makeFlag({ key: 'deep_flag', filters: { payloads: { true: payload } } })];
        const result = generateFlagTypes(flags);
        assert.ok(result.includes('Record<string, unknown>'), 'deep nesting should produce Record<string, unknown>');
    });

    test('array payload with typed values produces typed array', () => {
        const flags = [makeFlag({ key: 'arr_flag', filters: { payloads: { true: '[1,2,3]' } } })];
        const result = generateFlagTypes(flags);
        assert.ok(result.includes('number[]'), 'should produce number[]');
    });

    test('empty array payload produces unknown[]', () => {
        const flags = [makeFlag({ key: 'empty_arr_flag', filters: { payloads: { true: '[]' } } })];
        const result = generateFlagTypes(flags);
        assert.ok(result.includes('unknown[]'), 'empty array should produce unknown[]');
    });

    test('multivariate flag produces union of variant types', () => {
        const flags = [makeFlag({
            key: 'mv_flag',
            filters: { payloads: { control: '"a"', test: '{"x":1}' } }
        })];
        const result = generateFlagTypes(flags);
        assert.ok(result.includes('string'), 'union should contain string');
        assert.ok(result.includes('x'), 'union should contain x property');
        assert.ok(result.includes('|'), 'should be a union type');
    });

    test('flag key with hyphens is quoted in output', () => {
        const flags = [makeFlag({ key: 'my-flag', filters: {} })];
        const result = generateFlagTypes(flags);
        assert.ok(result.includes('"my-flag"'), 'hyphenated key should be quoted');
    });

    test('flag key that is a valid identifier is not quoted', () => {
        const flags = [makeFlag({ key: 'simple_flag', filters: {} })];
        const result = generateFlagTypes(flags);
        // Should contain simple_flag without extra quotes as property name
        assert.ok(result.includes('simple_flag'), 'valid identifier should appear in output');
    });

    test('unparseable JSON payload falls back to unknown', () => {
        const flags = [makeFlag({ key: 'bad_json', filters: { payloads: { true: '{not valid json' } } })];
        const result = generateFlagTypes(flags);
        assert.ok(result.includes('unknown'), 'bad JSON should fall back to unknown');
    });

    test('pre-parsed object payload (not a string) is used directly', () => {
        const flags = [makeFlag({ key: 'preparsed', filters: { payloads: { true: { theme: 'dark', version: 2 } } } })];
        const result = generateFlagTypes(flags);
        assert.ok(result.includes('theme'), 'pre-parsed object should produce inline type with theme');
        assert.ok(result.includes('version'), 'pre-parsed object should produce inline type with version');
    });

    test('multivariate flag deduplicates identical types in union', () => {
        const flags = [makeFlag({
            key: 'dedup_flag',
            filters: { payloads: { control: '"baseline"', test: '"variant"' } }
        })];
        const result = generateFlagTypes(flags);
        // Both variants produce "string" — union should only have one "string"
        // Get the type line for this flag
        const lines = result.split('\n');
        const flagLine = lines.find((l: string) => l.includes('dedup_flag'));
        assert.ok(flagLine, 'should have a line for dedup_flag');
        if (flagLine) {
            // Line format: "    type dedup_flag = string;" — split on "=" to get the type part
            const typeContent = flagLine.split('=').slice(1).join('=') ?? '';
            // Count occurrences of "string" in the type definition
            const stringCount = (typeContent.match(/\bstring\b/g) ?? []).length;
            assert.strictEqual(stringCount, 1, 'deduplicated union should only have one "string"');
        }
    });

    test('output contains correct structure with flag count', () => {
        const flags = [
            makeFlag({ key: 'flag_one', filters: {} }),
            makeFlag({ key: 'flag_two', filters: {} }),
        ];
        const result = generateFlagTypes(flags);
        assert.ok(result.includes('// Flags: 2'), 'should show flag count of 2');
        assert.ok(result.includes('declare namespace PostHogFlags'), 'should declare namespace');
    });
});
