import { FeatureFlag } from '../models/types';

// Maximum depth for inline object type generation
const MAX_INLINE_DEPTH = 3;

/**
 * Returns a quoted property name if the key is not a valid JS identifier,
 * otherwise returns the key as-is.
 */
function safePropertyName(key: string): string {
    // A valid JS identifier: starts with letter/underscore/$, followed by letters/digits/underscore/$
    if (/^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key)) {
        return key;
    }
    return `"${key}"`;
}

/**
 * Recursively infers a TypeScript type string from a parsed value.
 * @param value - The parsed value to infer a type from
 * @param depth - Current recursion depth (starts at 0)
 */
export function inferType(value: unknown, depth: number = 0): string {
    if (value === null) {
        return 'null';
    }
    if (value === undefined) {
        return 'unknown';
    }
    if (typeof value === 'string') {
        return 'string';
    }
    if (typeof value === 'number') {
        return 'number';
    }
    if (typeof value === 'boolean') {
        return 'boolean';
    }
    if (Array.isArray(value)) {
        if (value.length === 0) {
            return 'unknown[]';
        }
        return `${inferType(value[0], depth)}[]`;
    }
    if (typeof value === 'object') {
        if (depth >= MAX_INLINE_DEPTH) {
            return 'Record<string, unknown>';
        }
        const entries = Object.entries(value as Record<string, unknown>);
        if (entries.length === 0) {
            return 'Record<string, unknown>';
        }
        const props = entries
            .map(([k, v]) => `${safePropertyName(k)}: ${inferType(v, depth + 1)}`)
            .join('; ');
        return `{ ${props} }`;
    }
    return 'unknown';
}

/**
 * Extracts the payload value from a raw payload entry.
 * If the raw value is a string, attempts JSON.parse.
 * If the raw value is already a non-string primitive or object, uses it directly.
 * Returns undefined if the value is null/undefined (boolean flag).
 */
export function extractPayloadValue(raw: unknown): { parsed: unknown; ok: boolean } {
    if (raw === null || raw === undefined) {
        // null/undefined payload => boolean flag
        return { parsed: undefined, ok: false };
    }
    if (typeof raw === 'string') {
        try {
            return { parsed: JSON.parse(raw), ok: true };
        } catch {
            return { parsed: undefined, ok: false };
        }
    }
    // Already a parsed value (object, number, boolean, etc.)
    return { parsed: raw, ok: true };
}

/**
 * Determines the TypeScript type string for a single feature flag.
 */
function inferFlagType(flag: FeatureFlag): string {
    const payloads = flag.filters?.payloads as Record<string, unknown> | undefined | null;

    // No payloads or empty payloads object => boolean flag
    if (!payloads || typeof payloads !== 'object') {
        return 'boolean';
    }

    const keys = Object.keys(payloads);
    if (keys.length === 0) {
        return 'boolean';
    }

    // Boolean flag with a single "true" key
    if (keys.length === 1 && keys[0] === 'true') {
        const raw = payloads['true'];
        const { parsed, ok } = extractPayloadValue(raw);
        if (!ok) {
            // null/undefined payload or unparseable => boolean
            if (raw === null || raw === undefined) {
                return 'boolean';
            }
            // Unparseable JSON string
            return 'unknown';
        }
        return inferType(parsed);
    }

    // Multivariate flag: union of variant payload types
    const types: string[] = [];
    for (const key of keys) {
        const raw = payloads[key];
        const { parsed, ok } = extractPayloadValue(raw);
        if (!ok) {
            if (raw === null || raw === undefined) {
                types.push('boolean');
            } else {
                types.push('unknown');
            }
        } else {
            types.push(inferType(parsed));
        }
    }

    // Deduplicate
    const unique = [...new Set(types)];
    return unique.join(' | ');
}

/**
 * Generates a .posthog.d.ts TypeScript declaration file content from
 * an array of PostHog feature flags.
 *
 * @param flags - Array of FeatureFlag objects from the PostHog API
 * @returns A string containing the TypeScript declaration file content
 */
export function generateFlagTypes(flags: FeatureFlag[]): string {
    const activeFlags = flags.filter(f => !f.deleted);
    const timestamp = new Date().toISOString();
    const count = activeFlags.length;

    const lines: string[] = [
        '// .posthog.d.ts - generated by PostHog for VSCode',
        `// Generated: ${timestamp}`,
        `// Flags: ${count}`,
        '// Do not edit manually - re-run "PostHog: Generate Flag Types" to refresh.',
        '',
        'declare namespace PostHogFlags {',
    ];

    for (const flag of activeFlags) {
        const propName = safePropertyName(flag.key);
        const typeStr = inferFlagType(flag);
        lines.push(`    type ${propName} = ${typeStr};`);
    }

    lines.push('}');
    lines.push('');

    return lines.join('\n');
}
